export const inventory = [
  { id: 1, name: "Umbreon VMAX Alt Art", set: "Evolving Skies", number: "215/203", condition: "PSA 10", bought: 280, current: 420, image: "🌙", cardImage: "https://images.pokemontcg.io/swsh7/215_hires.png" },
  { id: 2, name: "Charizard ex", set: "Paldea Evolved", number: "199/193", condition: "PSA 9", bought: 95, current: 140, image: "🔥", cardImage: "https://images.pokemontcg.io/sv2/199_hires.png" },
  { id: 3, name: "Lugia V Alt Art", set: "Silver Tempest", number: "186/195", condition: "Raw NM", bought: 45, current: 62, image: "🌊", cardImage: "https://images.pokemontcg.io/swsh12/186_hires.png" },
  { id: 4, name: "Base Set Charizard", set: "Base Set 1999", number: "4/102", condition: "PSA 6", bought: 900, current: 1200, image: "🐉", cardImage: "https://images.pokemontcg.io/base1/4_hires.png" },
  { id: 5, name: "Rayquaza VMAX Alt Art", set: "Evolving Skies", number: "218/203", condition: "PSA 10", bought: 310, current: 390, image: "⚡", cardImage: "https://images.pokemontcg.io/swsh7/218_hires.png" },
  { id: 6, name: "Pikachu VMAX Rainbow", set: "Vivid Voltage", number: "188/185", condition: "PSA 9", bought: 75, current: 95, image: "⚡", cardImage: "https://images.pokemontcg.io/swsh4/188_hires.png" },
  { id: 7, name: "Mewtwo GX Rainbow", set: "Shining Legends", number: "78/73", condition: "Raw NM", bought: 28, current: 38, image: "🔮", cardImage: "https://images.pokemontcg.io/sm35/78_hires.png" },
  { id: 8, name: "Gengar VMAX Alt Art", set: "Fusion Strike", number: "271/264", condition: "PSA 10", bought: 145, current: 185, image: "👻", cardImage: "https://images.pokemontcg.io/swsh8/271_hires.png" },
  { id: 9, name: "Mew VMAX Alt Art", set: "Fusion Strike", number: "269/264", condition: "Raw NM", bought: 32, current: 48, image: "🌸", cardImage: "https://images.pokemontcg.io/swsh8/269_hires.png" },
  { id: 10, name: "Blaziken VMAX Alt Art", set: "Chilling Reign", number: "200/198", condition: "PSA 9", bought: 88, current: 110, image: "🔥", cardImage: "https://images.pokemontcg.io/swsh6/200_hires.png" },
  { id: 11, name: "Snorlax VMAX Rainbow", set: "Sword & Shield Base", number: "206/202", condition: "Raw NM", bought: 22, current: 29, image: "💤", cardImage: "https://images.pokemontcg.io/swsh1/206_hires.png" },
  { id: 12, name: "Dialga VSTAR Gold", set: "Astral Radiance", number: "214/189", condition: "Raw NM", bought: 18, current: 25, image: "🔵", cardImage: "https://images.pokemontcg.io/swsh10/214_hires.png" },
  { id: 13, name: "Arceus VSTAR Rainbow", set: "Brilliant Stars", number: "184/172", condition: "Raw NM", bought: 35, current: 42, image: "⭐", cardImage: "https://images.pokemontcg.io/swsh9/184_hires.png" },
  { id: 14, name: "Giratina V Alt Art", set: "Lost Origin", number: "182/196", condition: "PSA 10", bought: 195, current: 274, image: "🌀", cardImage: "https://images.pokemontcg.io/swsh11/182_hires.png" },
];

export const scannerData = [
  {
    id: 1, name: "Umbreon VMAX Alt Art", set: "Evolving Skies", image: "🌙", cardImage: "https://images.pokemontcg.io/swsh7/215_hires.png",
    ebay: 395, tcgplayer: 412, mercari: 380,
    lowestSource: "mercari", lowestPrice: 380,
    bestSell: "tcgplayer", bestPrice: 412,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $18–22 after fees.",
  },
  {
    id: 2, name: "Charizard ex", set: "Paldea Evolved", image: "🔥", cardImage: "https://images.pokemontcg.io/sv2/199_hires.png",
    ebay: 128, tcgplayer: 140, mercari: 115,
    lowestSource: "mercari", lowestPrice: 115,
    bestSell: "tcgplayer", bestPrice: 140,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $14–18 after fees.",
  },
  {
    id: 3, name: "Base Set Charizard PSA 6", set: "Base Set 1999", image: "🐉", cardImage: "https://images.pokemontcg.io/base1/4_hires.png",
    ebay: 1150, tcgplayer: 0, mercari: 980,
    lowestSource: "mercari", lowestPrice: 980,
    bestSell: "ebay", bestPrice: 1150,
    aiSignal: "Buy on Mercari → Sell on eBay. Est. profit: $105–140 after fees.",
  },
  {
    id: 4, name: "Giratina V Alt Art PSA 10", set: "Lost Origin", image: "🌀", cardImage: "https://images.pokemontcg.io/swsh11/182_hires.png",
    ebay: 255, tcgplayer: 274, mercari: 210,
    lowestSource: "mercari", lowestPrice: 210,
    bestSell: "tcgplayer", bestPrice: 274,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $42–55 after fees.",
  },
  {
    id: 5, name: "Gengar VMAX Alt Art PSA 10", set: "Fusion Strike", image: "👻", cardImage: "https://images.pokemontcg.io/swsh8/271_hires.png",
    ebay: 175, tcgplayer: 185, mercari: 145,
    lowestSource: "mercari", lowestPrice: 145,
    bestSell: "tcgplayer", bestPrice: 185,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $28–34 after fees.",
  },
  {
    id: 6, name: "Rayquaza VMAX Alt Art PSA 10", set: "Evolving Skies", image: "⚡", cardImage: "https://images.pokemontcg.io/swsh7/218_hires.png",
    ebay: 385, tcgplayer: 390, mercari: 355,
    lowestSource: "mercari", lowestPrice: 355,
    bestSell: "tcgplayer", bestPrice: 390,
    aiSignal: "Hold — margin below 10%. Wait for Mercari dip below $320.",
  },
  {
    id: 7, name: "Mew VMAX Alt Art", set: "Fusion Strike", image: "🌸", cardImage: "https://images.pokemontcg.io/swsh8/269_hires.png",
    ebay: 44, tcgplayer: 48, mercari: 38,
    lowestSource: "mercari", lowestPrice: 38,
    bestSell: "tcgplayer", bestPrice: 48,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $5–7 after fees.",
  },
  {
    id: 8, name: "Pikachu VMAX Rainbow PSA 9", set: "Vivid Voltage", image: "⚡", cardImage: "https://images.pokemontcg.io/swsh4/188_hires.png",
    ebay: 88, tcgplayer: 95, mercari: 72,
    lowestSource: "mercari", lowestPrice: 72,
    bestSell: "tcgplayer", bestPrice: 95,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $14–18 after fees.",
  },
  {
    id: 9, name: "Arceus VSTAR Rainbow", set: "Brilliant Stars", image: "⭐", cardImage: "https://images.pokemontcg.io/swsh9/184_hires.png",
    ebay: 40, tcgplayer: 42, mercari: 35,
    lowestSource: "mercari", lowestPrice: 35,
    bestSell: "tcgplayer", bestPrice: 42,
    aiSignal: "Hold — margin 20%. Buy if Mercari dips below $30.",
  },
  {
    id: 10, name: "Dialga VSTAR Gold", set: "Astral Radiance", image: "🔵", cardImage: "https://images.pokemontcg.io/swsh10/214_hires.png",
    ebay: 22, tcgplayer: 25, mercari: 17,
    lowestSource: "mercari", lowestPrice: 17,
    bestSell: "tcgplayer", bestPrice: 25,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $4–6 after fees.",
  },
  {
    id: 11, name: "Mewtwo GX Rainbow", set: "Shining Legends", image: "🔮", cardImage: "https://images.pokemontcg.io/sm35/78_hires.png",
    ebay: 36, tcgplayer: 38, mercari: 26,
    lowestSource: "mercari", lowestPrice: 26,
    bestSell: "tcgplayer", bestPrice: 38,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $7–9 after fees.",
  },
  {
    id: 12, name: "Lugia V Alt Art", set: "Silver Tempest", image: "🌊", cardImage: "https://images.pokemontcg.io/swsh12/186_hires.png",
    ebay: 58, tcgplayer: 62, mercari: 48,
    lowestSource: "mercari", lowestPrice: 48,
    bestSell: "tcgplayer", bestPrice: 62,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $8–10 after fees.",
  },
  {
    id: 13, name: "Blaziken VMAX Alt Art PSA 9", set: "Chilling Reign", image: "🔥", cardImage: "https://images.pokemontcg.io/swsh6/200_hires.png",
    ebay: 104, tcgplayer: 110, mercari: 85,
    lowestSource: "mercari", lowestPrice: 85,
    bestSell: "tcgplayer", bestPrice: 110,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $14–18 after fees.",
  },
  {
    id: 14, name: "Snorlax VMAX Rainbow", set: "Sword & Shield Base", image: "💤", cardImage: "https://images.pokemontcg.io/swsh1/206_hires.png",
    ebay: 27, tcgplayer: 29, mercari: 22,
    lowestSource: "mercari", lowestPrice: 22,
    bestSell: "tcgplayer", bestPrice: 29,
    aiSignal: "Buy on Mercari → Sell on TCGPlayer. Est. profit: $3–5 after fees.",
  },
];

export const listings = [
  { id: 1, name: "Umbreon VMAX Alt Art PSA 10", platform: "TCGPlayer", asking: 412, cost: 280, daysListed: 3, watchers: 12, status: "active" },
  { id: 2, name: "Base Set Charizard PSA 6", platform: "eBay", asking: 1199, cost: 900, daysListed: 7, watchers: 28, status: "active" },
  { id: 3, name: "Giratina V Alt Art PSA 10", platform: "TCGPlayer", asking: 274, cost: 195, daysListed: 2, watchers: 9, status: "active" },
  { id: 4, name: "Charizard ex", platform: "Mercari", asking: 138, cost: 95, daysListed: 15, watchers: 4, status: "active" },
  { id: 5, name: "Gengar VMAX Alt Art PSA 10", platform: "eBay", asking: 185, cost: 145, daysListed: 18, watchers: 6, status: "active" },
  { id: 6, name: "Pikachu VMAX Rainbow PSA 9", platform: "TCGPlayer", asking: 95, cost: 75, daysListed: 4, watchers: 7, status: "active" },
  { id: 7, name: "Lugia V Alt Art", platform: "Mercari", asking: 60, cost: 45, daysListed: 1, watchers: 3, status: "active" },
  { id: 8, name: "Blaziken VMAX Alt Art PSA 9", platform: "eBay", asking: 225, cost: 140, daysListed: 0, watchers: 0, status: "sold" },
];

export const activityFeed = [
  { id: 1, type: "sale", text: "Sold Blaziken VMAX Alt Art PSA 9 on eBay for $225", time: "2h ago", profit: 62 },
  { id: 2, type: "alert", text: "BUY SIGNAL: Giratina V Alt Art on Mercari — $210 (est. $52 flip)", time: "4h ago", profit: null },
  { id: 3, type: "purchase", text: "Purchased Giratina V Alt Art PSA 10 for $195", time: "5h ago", profit: null },
  { id: 4, type: "price", text: "Umbreon VMAX Alt Art up 4.2% on TCGPlayer ($396 → $412)", time: "6h ago", profit: null },
  { id: 5, type: "alert", text: "BUY SIGNAL: Charizard ex on Mercari — $115 (est. $16 flip)", time: "8h ago", profit: null },
  { id: 6, type: "sale", text: "Sold Mewtwo GX Rainbow on TCGPlayer for $38", time: "1d ago", profit: 9 },
  { id: 7, type: "purchase", text: "Purchased Charizard ex for $95", time: "1d ago", profit: null },
  { id: 8, type: "alert", text: "REPRICE: Charizard ex listing stale (15 days). Suggest $132.", time: "1d ago", profit: null },
];

export const chartData = [
  { day: "Jun 9", value: 2100 }, { day: "Jun 12", value: 2180 }, { day: "Jun 15", value: 2090 },
  { day: "Jun 18", value: 2250 }, { day: "Jun 21", value: 2310 }, { day: "Jun 24", value: 2280 },
  { day: "Jun 27", value: 2420 }, { day: "Jun 30", value: 2390 }, { day: "Jul 3", value: 2510 },
  { day: "Jul 6", value: 2620 }, { day: "Jul 7", value: 2695 }, { day: "Jul 8", value: 2758 },
];
